"use client"

import { useEffect, useMemo, useState } from "react"
import { BarChart3, CheckCircle2, Edit3, Megaphone, PencilLine, Plus, Search, Trash2, TrendingUp, X } from "lucide-react"
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { fetchApi } from "@/lib/api"

type Row = { platform:string; campaign:string; orders:number; revenue:number; spend:number; roas:number|null }
type Spend = { id:number; platform:string; campaign?:string|null; spendDate:string; amount:number; currency?:string }
const money=(value:number)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0}).format(value)
const initialForm={platform:"google",campaign:"",spendDate:new Date().toISOString().slice(0,10),amount:"",currency:"TRY"}

export default function RoasPage(){
 const [rows,setRows]=useState<Row[]>([]),[spends,setSpends]=useState<Spend[]>([]),[days,setDays]=useState(30),[platform,setPlatform]=useState("all"),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[form,setForm]=useState(initialForm),[editing,setEditing]=useState<number|null>(null),[deleteTarget,setDeleteTarget]=useState<Spend|null>(null)
 const load=async()=>{setLoading(true);try{const [report,records]=await Promise.all([fetchApi<Row[]>(`admin/roas/report?days=${days}`),fetchApi<Spend[]>(`admin/roas/spends?days=${days}`)]);setRows(report);setSpends(records)}catch(error){setMessage(error instanceof Error?error.message:"ROAS raporu yüklenemedi.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[days])
 const visibleRows=useMemo(()=>rows.filter(row=>(platform==="all"||row.platform===platform)&&`${row.platform} ${row.campaign}`.toLowerCase().includes(query.toLowerCase())),[rows,platform,query])
 const platforms=useMemo(()=>Array.from(new Set([...rows.map(x=>x.platform),...spends.map(x=>x.platform)])).sort(),[rows,spends])
 const totals=useMemo(()=>({revenue:visibleRows.reduce((sum,x)=>sum+x.revenue,0),spend:visibleRows.reduce((sum,x)=>sum+x.spend,0),orders:visibleRows.reduce((sum,x)=>sum+x.orders,0)}),[visibleRows]); const totalRoas=totals.spend?totals.revenue/totals.spend:null
 const save=async()=>{if(!(Number(form.amount)>0)){setMessage("Geçerli bir harcama tutarı girin.");return}try{await fetchApi("admin/roas/spends",{method:"POST",body:JSON.stringify({id:editing,...form,amount:Number(form.amount)})});setForm(initialForm);setEditing(null);setMessage("Harcama kaydedildi.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Harcama kaydedilemedi.")}}
 const edit=(item:Spend)=>{setEditing(item.id);setForm({platform:item.platform,campaign:item.campaign??"",spendDate:item.spendDate.slice(0,10),amount:String(item.amount),currency:item.currency??"TRY"});window.scrollTo({top:0,behavior:"smooth"})}
 const remove=async()=>{if(!deleteTarget)return;try{await fetchApi(`admin/roas/spends/${deleteTarget.id}`,{method:"DELETE"});setDeleteTarget(null);setMessage("Harcama kaydı silindi.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Harcama silinemedi.")}}
 return <main className="mx-auto max-w-7xl space-y-6 pb-10"><div className="rounded-2xl bg-gradient-to-br from-blue-950 via-slate-900 to-indigo-950 p-6 text-white shadow-lg md:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><div className="mb-3 flex items-center gap-2 text-sm text-blue-200"><Megaphone className="size-4" />Pazarlama analitiği</div><h1 className="text-3xl font-bold tracking-tight">ROAS raporu</h1><p className="mt-2 max-w-2xl text-sm text-slate-300">UTM kaynaklı ödenmiş sipariş cirosunu reklam harcamasıyla eşleştirerek kanalların gerçek getirisini görün.</p></div><select className="h-10 rounded-md border border-white/20 bg-white/10 px-3 text-sm text-white" value={days} onChange={e=>setDays(Number(e.target.value))}><option className="text-slate-900" value={7}>Son 7 gün</option><option className="text-slate-900" value={30}>Son 30 gün</option><option className="text-slate-900" value={90}>Son 90 gün</option></select></div><div className="mt-7 grid grid-cols-2 gap-3 border-t border-white/10 pt-5 md:grid-cols-4"><div><p className="text-xs text-slate-400">Atfedilen ciro</p><p className="mt-1 text-xl font-semibold">{money(totals.revenue)}</p></div><div><p className="text-xs text-slate-400">Reklam harcaması</p><p className="mt-1 text-xl font-semibold">{money(totals.spend)}</p></div><div><p className="text-xs text-slate-400">Toplam sipariş</p><p className="mt-1 text-xl font-semibold">{totals.orders}</p></div><div><p className="text-xs text-slate-400">Ortalama ROAS</p><p className="mt-1 text-xl font-semibold">{totalRoas===null?"—":`${totalRoas.toFixed(2)}x`}</p></div></div></div>
 {message&&<div className="flex items-center gap-2 rounded-lg border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-900"><CheckCircle2 className="size-4" />{message}</div>}
 <Card className="border-slate-200 p-5 shadow-sm md:p-7"><div className="mb-5 flex items-start justify-between border-b pb-5"><div><h2 className="text-xl font-bold text-slate-900">{editing?"Harcama kaydını düzenle":"Manuel harcama ekle"}</h2><p className="mt-1 text-sm text-muted-foreground">Platform bağlantısı tamamlanana kadar harcamaları günlük olarak kaydedin.</p></div>{editing&&<Button variant="ghost" onClick={()=>{setEditing(null);setForm(initialForm)}}><X className="mr-2 size-4" />İptal</Button>}</div><div className="grid gap-4 md:grid-cols-5"><div className="space-y-1.5"><Label>Platform</Label><select className="h-10 w-full rounded-md border bg-white px-3 text-sm" value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}><option value="google">Google</option><option value="meta">Meta</option><option value="tiktok">TikTok</option><option value="other">Diğer</option></select></div><div className="space-y-1.5"><Label>Kampanya adı</Label><Input value={form.campaign} onChange={e=>setForm({...form,campaign:e.target.value})} placeholder="UTM kampanya adı" /></div><div className="space-y-1.5"><Label>Tarih</Label><Input type="date" value={form.spendDate} onChange={e=>setForm({...form,spendDate:e.target.value})} /></div><div className="space-y-1.5"><Label>Harcama (₺)</Label><Input type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="0,00" /></div><div className="flex items-end"><Button className="w-full" onClick={()=>void save()}><Plus className="mr-2 size-4" />{editing?"Güncelle":"Kaydet"}</Button></div></div></Card>
 <Card className="overflow-hidden border-slate-200 shadow-sm"><div className="flex flex-col gap-4 border-b p-5 md:flex-row md:items-center md:justify-between md:px-7"><div><div className="flex items-center gap-2"><BarChart3 className="size-5 text-blue-700" /><h2 className="font-bold text-slate-900">Kampanya performansı</h2></div><p className="mt-1 text-sm text-muted-foreground">Gelir, harcama ve ROAS değerleri aynı UTM platformu/kampanya adına göre eşleştirilir.</p></div><div className="flex flex-wrap gap-2"><select className="h-10 rounded-md border bg-white px-3 text-sm" value={platform} onChange={e=>setPlatform(e.target.value)}><option value="all">Tüm platformlar</option>{platforms.map(item=><option key={item} value={item}>{item}</option>)}</select><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="w-56 pl-9" placeholder="Kampanya ara" value={query} onChange={e=>setQuery(e.target.value)} /></div></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 md:px-7">Platform</th><th className="px-5 py-3">Kampanya</th><th className="px-5 py-3">Sipariş</th><th className="px-5 py-3">Ciro</th><th className="px-5 py-3">Harcama</th><th className="px-5 py-3 md:px-7">ROAS</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="px-5 py-12 text-center text-muted-foreground">Veriler yükleniyor…</td></tr>:visibleRows.length?visibleRows.map(row=><tr key={`${row.platform}-${row.campaign}`} className="border-t transition-colors hover:bg-slate-50/80"><td className="px-5 py-4 md:px-7"><Badge variant="secondary" className="capitalize">{row.platform}</Badge></td><td className="px-5 py-4 font-medium text-slate-900">{row.campaign}</td><td className="px-5 py-4">{row.orders}</td><td className="px-5 py-4 font-semibold text-emerald-700">{money(row.revenue)}</td><td className="px-5 py-4 text-slate-700">{money(row.spend)}</td><td className="px-5 py-4 md:px-7"><Badge className={row.roas===null?"bg-slate-100 text-slate-600 hover:bg-slate-100":row.roas>=3?"bg-emerald-100 text-emerald-800 hover:bg-emerald-100":row.roas>=1?"bg-amber-100 text-amber-800 hover:bg-amber-100":"bg-rose-100 text-rose-800 hover:bg-rose-100"}>{row.roas===null?"Harcama yok":`${row.roas}x`}</Badge></td></tr>):<tr><td colSpan={6} className="px-5 py-14 text-center text-muted-foreground"><TrendingUp className="mx-auto mb-3 size-7 text-slate-300" />Filtreye uygun performans verisi bulunamadı.</td></tr>}</tbody></table></div></Card>
 <Card className="overflow-hidden border-slate-200 shadow-sm"><div className="flex items-center justify-between border-b p-5 md:px-7"><div><h2 className="font-bold text-slate-900">Kaydedilen harcamalar</h2><p className="mt-1 text-sm text-muted-foreground">Düzeltmek için kaydı düzenleyin; silinen kayıt rapordan çıkarılır.</p></div><Badge variant="secondary">{spends.length} kayıt</Badge></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 md:px-7">Tarih</th><th className="px-5 py-3">Platform</th><th className="px-5 py-3">Kampanya</th><th className="px-5 py-3">Tutar</th><th className="px-5 py-3 md:px-7" /></tr></thead><tbody>{spends.length?spends.map(item=><tr key={item.id} className="border-t"><td className="px-5 py-3 md:px-7">{new Date(item.spendDate).toLocaleDateString("tr-TR")}</td><td className="px-5 py-3 capitalize">{item.platform}</td><td className="px-5 py-3">{item.campaign||"—"}</td><td className="px-5 py-3 font-medium">{money(item.amount)}</td><td className="px-5 py-3 text-right md:px-7"><Button size="sm" variant="outline" onClick={()=>edit(item)}><Edit3 className="mr-1.5 size-3.5" />Düzenle</Button><Button size="icon" variant="ghost" className="ml-1 text-rose-600 hover:bg-rose-50 hover:text-rose-700" onClick={()=>setDeleteTarget(item)}><Trash2 className="size-4" /></Button></td></tr>):<tr><td colSpan={5} className="px-5 py-12 text-center text-muted-foreground">Bu tarih aralığında kaydedilmiş harcama yok.</td></tr>}</tbody></table></div></Card>
 <AlertDialog open={!!deleteTarget} onOpenChange={open=>!open&&setDeleteTarget(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Harcama kaydı silinsin mi?</AlertDialogTitle><AlertDialogDescription>Bu işlem ilgili tutarı ROAS raporundan kalıcı olarak çıkarır.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Vazgeç</AlertDialogCancel><AlertDialogAction className="bg-rose-600 hover:bg-rose-700" onClick={()=>void remove()}><Trash2 className="mr-2 size-4" />Sil</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>
}
