"use client"
import { useState } from "react"
import { CheckCircle2, KeyRound, LockKeyhole, Plus, ShieldAlert, UsersRound } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { adminRolesApi } from "@/lib/api"
export default function RolesPage(){const [roleName,setRoleName]=useState("");const [message,setMessage]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [loading,setLoading]=useState(false);const create=async()=>{const name=roleName.trim();if(!name){setError("Rol adı zorunludur.");return}try{setLoading(true);setError(null);setMessage(null);const res=await adminRolesApi.createRole(name);if(res.success===false)throw new Error(res.message);setMessage("Rol oluşturuldu. Kullanıcı düzenleme ekranından bu rolü atayabilirsiniz.");setRoleName("")}catch(e){setError(e instanceof Error?e.message:"Rol oluşturulamadı")}finally{setLoading(false)}};return <main className="mx-auto max-w-5xl space-y-6 pb-10"><div className="rounded-2xl bg-gradient-to-br from-indigo-950 via-slate-900 to-slate-950 p-6 text-white shadow-lg md:p-8"><div className="flex items-end justify-between gap-5"><div><div className="mb-3 flex items-center gap-2 text-sm text-indigo-200"><KeyRound className="size-4"/>Erişim yönetimi</div><h1 className="text-3xl font-bold tracking-tight">Roller ve yetkiler</h1><p className="mt-2 max-w-2xl text-sm text-slate-300">Yönetim paneline erişecek ekip üyeleri için kontrollü rol yapısı oluşturun.</p></div><div className="rounded-xl border border-white/10 bg-white/10 p-3"><LockKeyhole className="size-5 text-indigo-200"/></div></div></div>{message&&<div className="flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-900"><CheckCircle2 className="size-4"/>{message}</div>}{error&&<div className="flex items-center gap-2 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-900"><ShieldAlert className="size-4"/>{error}</div>}<Card className="border-slate-200 p-6 shadow-sm"><div className="mb-6 flex items-start gap-3 border-b pb-5"><div className="rounded-lg bg-indigo-50 p-2 text-indigo-700"><UsersRound className="size-5"/></div><div><h2 className="text-xl font-bold text-slate-900">Yeni rol oluştur</h2><p className="mt-1 text-sm text-muted-foreground">Rol adı kısa, açık ve ekipteki sorumluluğu anlatır olmalıdır; örn. <strong>İçerik Editörü</strong>.</p></div></div><div className="max-w-xl space-y-2"><Label>Rol adı</Label><div className="flex gap-2"><Input placeholder="Örn. Katalog Yöneticisi" value={roleName} onChange={e=>setRoleName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void create()}/><Button onClick={()=>void create()} disabled={loading}><Plus className="mr-2 size-4"/>{loading?"Oluşturuluyor…":"Rol oluştur"}</Button></div></div></Card><Card className="border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold text-amber-950">Güvenli yetkilendirme notu</h2><p className="mt-1 text-sm text-amber-900">Yeni rol oluşturmak tek başına erişim vermez. Rolü kullanıcı düzenleme ekranından ilgili ekip üyesine atayın; yalnız gerekli yetkileri tanımlayın.</p></Card></main>}
