"use client"

import { useEffect, useMemo, useState, type ReactNode } from "react"
import { BarChart3, CalendarDays, CheckCircle2, CopyPlus, Edit3, Gift, Layers3, Plus, Sparkles, Trash2, X } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { fetchApi } from "@/lib/api"

type Campaign = { id:number; name:string; couponCode?:string|null; startsAt:string; endsAt?:string|null; priority:number; isStackable:boolean; firstOrderOnly:boolean; minimumCartAmount?:number|null; minimumQuantity?:number|null; payQuantity?:number|null; targetProductId?:number|null; targetCategoryId?:number|null; targetProductTagId?:number|null; rewardType:number; rewardValue:number; rewardProductId?:number|null; bundleProductIds?:string|null; bundlePrice?:number|null; usageLimit?:number|null; usageLimitPerCustomer?:number|null; usageCount:number; isActive:boolean }
type Form = Omit<Campaign,"id"|"usageCount">
type Report = { campaignId:number; campaignName:string; usageCount:number; successfulOrderCount:number; attributedDiscountTotal:number; attributedRevenue:number }
type Lookup = { id:number; name:string }; type Lookups = { products:Lookup[]; categories:Lookup[]; tags:Lookup[] }
const now = () => new Date().toISOString().slice(0, 16)
const blank:Form = { name:"", couponCode:"", startsAt:now(), endsAt:null, priority:0, isStackable:false, firstOrderOnly:false, minimumCartAmount:null, minimumQuantity:null, payQuantity:null, targetProductId:null, targetCategoryId:null, targetProductTagId:null, rewardType:0, rewardValue:0, rewardProductId:null, bundleProductIds:"", bundlePrice:null, usageLimit:null, usageLimitPerCustomer:null, isActive:true }
const reward = ["% indirim", "₺ indirim", "Ücretsiz kargo", "Hediye ürün", "X al Y öde", "Set fiyatı"]
const nullable = (value:string) => value === "" ? null : Number(value)
const money = (value:number) => new Intl.NumberFormat("tr-TR", { style:"currency", currency:"TRY", maximumFractionDigits:0 }).format(value)
function Field({ label, hint, children }:{ label:string; hint?:string; children:ReactNode }) { return <div className="space-y-1.5"><Label className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</Label>{children}{hint && <p className="text-xs text-muted-foreground">{hint}</p>}</div> }
function SectionTitle({ icon, title, description }:{ icon:ReactNode; title:string; description:string }) { return <div className="mb-5 flex items-start gap-3"><div className="rounded-lg bg-blue-50 p-2 text-blue-700">{icon}</div><div><h2 className="font-semibold text-slate-900">{title}</h2><p className="mt-0.5 text-sm text-muted-foreground">{description}</p></div></div> }

export default function CampaignSettingsPage() {
  const [items, setItems] = useState<Campaign[]>([]); const [report, setReport] = useState<Report[]>([]); const [lookups, setLookups] = useState<Lookups>({ products:[], categories:[], tags:[] }); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [form, setForm] = useState<Form>(blank); const [editing, setEditing] = useState<number | null>(null); const [message, setMessage] = useState(""); const [bulkPrefix, setBulkPrefix] = useState("KUPON"); const [bulkCount, setBulkCount] = useState(10)
  const set = <K extends keyof Form>(key:K, value:Form[K]) => setForm(old => ({ ...old, [key]:value }))
  const load = async () => { const query = new URLSearchParams(); if (from) query.set("from", from); if (to) query.set("to", to); const [campaignResponse, reportResponse, lookupResponse] = await Promise.all([fetchApi<{data:Campaign[]}>("/admin/campaigns"), fetchApi<{data:Report[]}>(`/admin/campaigns/report?${query}`), fetchApi<Lookups>("/admin/campaigns/lookups")]); setItems(campaignResponse.data ?? []); setReport(reportResponse.data ?? []); setLookups(lookupResponse) }
  useEffect(() => { load().catch(() => setMessage("Kampanyalar yüklenemedi.")) }, [])
  const totals = useMemo(() => ({ active:items.filter(x => x.isActive).length, usage:items.reduce((sum,x) => sum+x.usageCount,0), revenue:report.reduce((sum,x) => sum+x.attributedRevenue,0), discount:report.reduce((sum,x) => sum+x.attributedDiscountTotal,0) }), [items,report])
  const save = async () => { if (!form.name.trim()) { setMessage("Kampanya adı zorunludur."); return }; try { await fetchApi(editing ? `/admin/campaigns/${editing}` : "/admin/campaigns", { method:editing ? "PUT" : "POST", body:JSON.stringify({ ...form, startsAt:new Date(form.startsAt).toISOString(), endsAt:form.endsAt ? new Date(form.endsAt).toISOString() : null }) }); setForm(blank); setEditing(null); setMessage("Kampanya başarıyla kaydedildi."); await load() } catch (error) { setMessage(error instanceof Error ? error.message : "Kampanya kaydedilemedi.") } }
  const edit = (item:Campaign) => { const { id,usageCount,...data } = item; setEditing(id); setForm({ ...data, startsAt:item.startsAt.slice(0,16), endsAt:item.endsAt?.slice(0,16) ?? null }); window.scrollTo({ top:0, behavior:"smooth" }) }
  const cancel = () => { setEditing(null); setForm(blank); setMessage("") }
  const remove = async (id:number) => { if (!confirm("Kampanya silinsin mi? Bu işlem geri alınamaz.")) return; try { await fetchApi(`/admin/campaigns/${id}`, { method:"DELETE" }); setMessage("Kampanya silindi."); await load() } catch (error) { setMessage(error instanceof Error ? error.message : "Kampanya silinemedi.") } }
  const generateCodes = async () => { if (!editing) return; try { const response = await fetchApi<{data:string[]}>(`/admin/campaigns/${editing}/coupon-codes`, { method:"POST", body:JSON.stringify({ prefix:bulkPrefix, count:bulkCount }) }); const csv="Kupon Kodu\n"+(response.data??[]).map(code => `\"${code}\"`).join("\n"); const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})); const link=document.createElement("a"); link.href=url; link.download=`kampanya-${editing}-kuponlari.csv`; link.click(); URL.revokeObjectURL(url); setMessage(`${response.data?.length??0} kupon üretildi ve CSV indirildi.`); await load() } catch(error) { setMessage(error instanceof Error ? error.message : "Kupon üretilemedi.") } }
  const SelectLookup = ({value,onChange,items,empty,disabled}:{value:number|null|undefined;onChange:(v:number|null)=>void;items:Lookup[];empty:string;disabled?:boolean}) => <select disabled={disabled} className="h-10 w-full rounded-md border bg-white px-3 text-sm disabled:cursor-not-allowed disabled:opacity-50" value={value??""} onChange={e=>onChange(nullable(e.target.value))}><option value="">{empty}</option>{items.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>
  return <div className="mx-auto max-w-7xl space-y-6 pb-10">
    <div className="overflow-hidden rounded-2xl bg-gradient-to-br from-slate-950 via-slate-900 to-blue-950 p-6 text-white shadow-lg md:p-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="mb-3 flex items-center gap-2 text-sm text-blue-200"><Sparkles className="size-4" />Satış büyütme merkezi</div><h1 className="text-3xl font-bold tracking-tight">Kampanyalar</h1><p className="mt-2 max-w-2xl text-sm text-slate-300">İndirimleri, kuponları ve sepet teşviklerini tek merkezden planlayın ve sonuçlarını takip edin.</p></div><Button className="bg-white text-slate-900 hover:bg-slate-100" onClick={cancel}><Plus className="mr-2 size-4" />Yeni kampanya</Button></div><div className="mt-7 grid grid-cols-2 gap-3 border-t border-white/10 pt-5 md:grid-cols-4">{[["Aktif kampanya",String(totals.active)],["Toplam kullanım",String(totals.usage)],["Atfedilen ciro",money(totals.revenue)],["Verilen indirim",money(totals.discount)]].map(([label,value])=><div key={label}><p className="text-xs text-slate-400">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</div></div>
    {message && <div className="flex items-center gap-2 rounded-lg border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-900"><CheckCircle2 className="size-4" />{message}</div>}
    <Card className="border-slate-200 p-5 shadow-sm md:p-7"><div className="mb-6 flex flex-col gap-3 border-b pb-5 md:flex-row md:items-center md:justify-between"><div><h2 className="text-xl font-bold text-slate-900">{editing ? "Kampanyayı düzenle" : "Yeni kampanya oluştur"}</h2><p className="mt-1 text-sm text-muted-foreground">Önce koşulu, ardından müşterinin alacağı avantajı belirleyin.</p></div>{editing && <Button variant="ghost" onClick={cancel}><X className="mr-2 size-4" />Düzenlemeyi kapat</Button>}</div><div className="space-y-7">
      <section><SectionTitle icon={<Gift className="size-4" />} title="Kampanya tanımı" description="Müşterinin göreceği isim, kupon ve öncelik bilgileri." /><div className="grid gap-4 md:grid-cols-3"><Field label="Kampanya adı"><Input placeholder="Örn. İlk siparişe özel" value={form.name} onChange={e=>set("name",e.target.value)} /></Field><Field label="Kupon kodu" hint="Boş bırakılırsa otomatik uygulanır."><Input placeholder="Örn. HOSGELDIN10" value={form.couponCode??""} onChange={e=>set("couponCode",e.target.value.toUpperCase())} /></Field><Field label="Öncelik" hint="Yüksek değer önce değerlendirilir."><Input type="number" value={form.priority} onChange={e=>set("priority",Number(e.target.value))} /></Field></div></section>
      <section className="rounded-xl bg-slate-50 p-4 md:p-5"><SectionTitle icon={<Sparkles className="size-4" />} title="Avantaj" description="Sepette uygulanacak ödül tipini ve tutarını seçin." /><div className="grid gap-4 md:grid-cols-3"><Field label="Ödül tipi"><select className="h-10 w-full rounded-md border bg-white px-3 text-sm" value={form.rewardType} onChange={e=>set("rewardType",Number(e.target.value))}>{reward.map((name,i)=><option key={name} value={i}>{name}</option>)}</select></Field><Field label={form.rewardType===0?"İndirim oranı (%)":form.rewardType===3?"Hediye adedi":"Ödül değeri"}><Input type="number" min="0" step="0.01" disabled={form.rewardType===2} value={form.rewardValue} onChange={e=>set("rewardValue",Number(e.target.value))} /></Field><Field label="Minimum sepet tutarı"><Input type="number" min="0" placeholder="Sınır yok" value={form.minimumCartAmount??""} onChange={e=>set("minimumCartAmount",nullable(e.target.value))} /></Field></div><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label={form.rewardType===4?"Alınacak adet (X)":"Minimum ürün adedi"}><Input type="number" min="1" disabled={form.rewardType!==4&&form.rewardType!==3} value={form.minimumQuantity??""} onChange={e=>set("minimumQuantity",nullable(e.target.value))} /></Field><Field label="Ödenecek adet (Y)"><Input type="number" min="0" disabled={form.rewardType!==4} value={form.payQuantity??""} onChange={e=>set("payQuantity",nullable(e.target.value))} /></Field><Field label="Hediye ürün"><SelectLookup disabled={form.rewardType!==3} value={form.rewardProductId} onChange={v=>set("rewardProductId",v)} items={lookups.products} empty="Ürün seçin" /></Field></div><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Set ürün ID'leri" hint="Virgülle ayırın: 12, 25"><Input disabled={form.rewardType!==5} placeholder="12, 25" value={form.bundleProductIds??""} onChange={e=>set("bundleProductIds",e.target.value)} /></Field><Field label="Set fiyatı"><Input type="number" min="0" step="0.01" disabled={form.rewardType!==5} value={form.bundlePrice??""} onChange={e=>set("bundlePrice",nullable(e.target.value))} /></Field></div></section>
      <section><SectionTitle icon={<Layers3 className="size-4" />} title="Hedefleme ve kurallar" description="Kampanyayı ürün, kategori veya etikete sınırlayabilir; kullanım koşullarını belirleyebilirsiniz." /><div className="grid gap-4 md:grid-cols-3"><Field label="Hedef ürün"><SelectLookup value={form.targetProductId} onChange={v=>set("targetProductId",v)} items={lookups.products} empty="Tüm ürünler" /></Field><Field label="Hedef kategori"><SelectLookup value={form.targetCategoryId} onChange={v=>set("targetCategoryId",v)} items={lookups.categories} empty="Tüm kategoriler" /></Field><Field label="Hedef etiket"><SelectLookup value={form.targetProductTagId} onChange={v=>set("targetProductTagId",v)} items={lookups.tags} empty="Tüm etiketler" /></Field></div><div className="mt-5 grid gap-4 md:grid-cols-4"><Field label="Toplam kullanım limiti"><Input type="number" min="1" placeholder="Sınırsız" value={form.usageLimit??""} onChange={e=>set("usageLimit",nullable(e.target.value))} /></Field><Field label="Müşteri başı limit"><Input type="number" min="1" placeholder="Sınırsız" value={form.usageLimitPerCustomer??""} onChange={e=>set("usageLimitPerCustomer",nullable(e.target.value))} /></Field><Field label="Başlangıç"><Input type="datetime-local" value={form.startsAt} onChange={e=>set("startsAt",e.target.value)} /></Field><Field label="Bitiş"><Input type="datetime-local" value={form.endsAt??""} onChange={e=>set("endsAt",e.target.value||null)} /></Field></div><div className="mt-5 flex flex-wrap gap-x-7 gap-y-4 rounded-lg border bg-slate-50 px-4 py-3"><label className="flex items-center gap-2 text-sm font-medium"><Switch checked={form.isActive} onCheckedChange={v=>set("isActive",v)} />Aktif</label><label className="flex items-center gap-2 text-sm font-medium"><Switch checked={form.isStackable} onCheckedChange={v=>set("isStackable",v)} />Diğer kampanyalarla birleşebilir</label><label className="flex items-center gap-2 text-sm font-medium"><Switch checked={form.firstOrderOnly} onCheckedChange={v=>set("firstOrderOnly",v)} />Yalnızca ilk sipariş</label></div></section>
      <div className="flex flex-wrap items-center justify-between gap-3 border-t pt-5"><p className="text-xs text-muted-foreground">Kayıttan sonra kampanya sepetteki uygun koşullarda devreye girer.</p><div className="flex gap-2"><Button variant="outline" onClick={cancel}>Temizle</Button><Button onClick={save}><CheckCircle2 className="mr-2 size-4" />{editing?"Değişiklikleri kaydet":"Kampanyayı oluştur"}</Button></div></div>{editing!==null&&<div className="rounded-xl border border-dashed border-blue-200 bg-blue-50/60 p-4"><div className="mb-3 flex items-center gap-2 font-semibold text-blue-950"><CopyPlus className="size-4" />Toplu kupon üretimi</div><div className="flex flex-wrap items-end gap-3"><Field label="Kupon öneki"><Input value={bulkPrefix} onChange={e=>setBulkPrefix(e.target.value.toUpperCase())} /></Field><Field label="Adet"><Input type="number" min="1" max="1000" value={bulkCount} onChange={e=>setBulkCount(Number(e.target.value))} /></Field><Button variant="outline" onClick={generateCodes}>Üret ve CSV indir</Button></div></div>}</div></Card>
    <Card className="border-slate-200 p-5 shadow-sm md:p-7"><div className="flex flex-col gap-4 border-b pb-5 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2"><BarChart3 className="size-5 text-blue-700" /><h2 className="text-xl font-bold text-slate-900">Kampanya performansı</h2></div><p className="mt-1 text-sm text-muted-foreground">İndirim ve ciro, çoklu kampanyalı siparişlerde eşit paylaştırılır.</p></div><div className="flex flex-wrap gap-2"><Input className="w-auto" type="date" value={from} onChange={e=>setFrom(e.target.value)} /><Input className="w-auto" type="date" value={to} onChange={e=>setTo(e.target.value)} /><Button variant="outline" onClick={()=>void load()}><CalendarDays className="mr-2 size-4" />Uygula</Button></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="rounded-l-lg px-4 py-3">Kampanya</th><th className="px-4 py-3">Sipariş</th><th className="px-4 py-3">Kullanım</th><th className="px-4 py-3">İndirim</th><th className="rounded-r-lg px-4 py-3">Atfedilen ciro</th></tr></thead><tbody>{report.length?report.map(item=><tr key={item.campaignId} className="border-b last:border-0"><td className="px-4 py-4 font-medium text-slate-900">{item.campaignName}</td><td className="px-4 py-4">{item.successfulOrderCount}</td><td className="px-4 py-4">{item.usageCount}</td><td className="px-4 py-4 text-rose-700">{money(item.attributedDiscountTotal)}</td><td className="px-4 py-4 font-semibold text-emerald-700">{money(item.attributedRevenue)}</td></tr>):<tr><td colSpan={5} className="px-4 py-10 text-center text-muted-foreground">Seçilen tarih aralığında kampanya verisi yok.</td></tr>}</tbody></table></div></Card>
    <Card className="overflow-hidden border-slate-200 shadow-sm"><div className="flex items-center justify-between border-b p-5 md:px-7"><div><h2 className="font-bold text-slate-900">Tanımlı kampanyalar</h2><p className="mt-1 text-sm text-muted-foreground">Yayındaki kampanyaları yönetin ve kullanımını takip edin.</p></div><Badge variant="secondary">{items.length} kampanya</Badge></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 md:px-7">Kampanya</th><th className="px-5 py-3">Avantaj</th><th className="px-5 py-3">Durum</th><th className="px-5 py-3">Kullanım</th><th className="px-5 py-3">Dönem</th><th className="px-5 py-3 md:px-7" /></tr></thead><tbody>{items.length?items.map(item=><tr key={item.id} className="border-t transition-colors hover:bg-slate-50/80"><td className="px-5 py-4 md:px-7"><p className="font-semibold text-slate-900">{item.name}</p>{item.couponCode&&<p className="mt-1 font-mono text-xs text-slate-500">{item.couponCode}</p>}</td><td className="px-5 py-4">{reward[item.rewardType]}{item.rewardType!==2&&<span className="ml-1 text-slate-500">{item.rewardType===0?`%${item.rewardValue}`:money(item.rewardValue)}</span>}</td><td className="px-5 py-4"><Badge className={item.isActive?"bg-emerald-100 text-emerald-800 hover:bg-emerald-100":"bg-slate-100 text-slate-600 hover:bg-slate-100"}>{item.isActive?"Aktif":"Pasif"}</Badge></td><td className="px-5 py-4"><span className="font-medium">{item.usageCount}</span><span className="text-slate-400">{item.usageLimit?` / ${item.usageLimit}`:" / ∞"}</span></td><td className="px-5 py-4 text-xs text-slate-500">{new Date(item.startsAt).toLocaleDateString("tr-TR")}<br />{item.endsAt?new Date(item.endsAt).toLocaleDateString("tr-TR"):"Süresiz"}</td><td className="px-5 py-4 text-right md:px-7"><Button size="sm" variant="outline" onClick={()=>edit(item)}><Edit3 className="mr-2 size-3.5" />Düzenle</Button><Button size="icon" variant="ghost" className="ml-1 text-rose-600 hover:bg-rose-50 hover:text-rose-700" onClick={()=>void remove(item.id)} aria-label={`${item.name} kampanyasını sil`}><Trash2 className="size-4" /></Button></td></tr>):<tr><td colSpan={6} className="px-5 py-12 text-center text-muted-foreground">Henüz kampanya oluşturulmamış.</td></tr>}</tbody></table></div></Card>
  </div>
}
