"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import { AlertCircle, CheckCircle2, ExternalLink, FileSearch, Link2, Pencil, Plus, RefreshCw, Search, Trash2, X } from "lucide-react"
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { fetchApi } from "@/lib/api"

type DomainRoute = { id:number; slug:string; entityType:string }
type RedirectRule = { id:number; sourcePath:string; targetPath:string; statusCode:number; isActive:boolean }
type Paged<T> = { items:T[]; pageNumber:number; totalCount:number }
const blank = { sourcePath:"", targetPath:"", statusCode:301, isActive:true }

export default function RoutesPage() {
  const [data,setData] = useState<Paged<DomainRoute>>({ items:[],pageNumber:1,totalCount:0 })
  const [redirects,setRedirects] = useState<RedirectRule[]>([])
  const [q,setQ] = useState(""); const [form,setForm] = useState(blank); const [editing,setEditing] = useState<number|null>(null); const [message,setMessage] = useState(""); const [loading,setLoading] = useState(true); const [rebuilding,setRebuilding] = useState(false); const [deleteTarget,setDeleteTarget] = useState<RedirectRule|null>(null)
  const load = useCallback(async () => { setLoading(true); try { const [routes,rules] = await Promise.all([fetchApi<Paged<DomainRoute>>(`admin/routes?pageNumber=1&pageSize=50${q ? `&q=${encodeURIComponent(q)}` : ""}`),fetchApi<RedirectRule[]>("admin/routes/redirects")]); setData(routes); setRedirects(rules) } catch { setMessage("URL verileri yüklenemedi.") } finally { setLoading(false) } },[q])
  useEffect(() => { void load() },[load])
  const normalizedPreview = useMemo(() => { const source=form.sourcePath.trim(); const target=form.targetPath.trim(); return source && target ? `${source.startsWith("/") ? source : "/"+source} → ${target.startsWith("/") ? target : "/"+target}` : null },[form.sourcePath,form.targetPath])
  const save = async () => { if (!form.sourcePath.trim() || !form.targetPath.trim()) { setMessage("Kaynak ve hedef URL zorunludur."); return } try { await fetchApi("admin/routes/redirects",{method:"POST",body:JSON.stringify({id:editing??0,...form})}); setForm(blank); setEditing(null); setMessage("Yönlendirme kaydedildi."); await load() } catch(e) { setMessage(e instanceof Error?e.message:"Yönlendirme kaydedilemedi.") } }
  const edit = (item:RedirectRule) => { setEditing(item.id); setForm({ sourcePath:item.sourcePath,targetPath:item.targetPath,statusCode:item.statusCode,isActive:item.isActive }); window.scrollTo({top:0,behavior:"smooth"}) }
  const remove = async () => { if(!deleteTarget) return; try { await fetchApi(`admin/routes/redirects/${deleteTarget.id}`,{method:"DELETE"}); setDeleteTarget(null); setMessage("Yönlendirme kuralı silindi."); await load() } catch(e) { setMessage(e instanceof Error?e.message:"Kural silinemedi.") } }
  const rebuild = async () => { setRebuilding(true); try { const response=await fetchApi<{message?:string}>("admin/routes/rebuild",{method:"POST"}); setMessage(response.message??"URL envanteri yeniden oluşturuldu."); await load() } catch(e) { setMessage(e instanceof Error?e.message:"URL envanteri oluşturulamadı.") } finally { setRebuilding(false) } }
  const activeCount=redirects.filter(item=>item.isActive).length
  return <main className="mx-auto max-w-7xl space-y-6 pb-10">
    <div className="rounded-2xl bg-gradient-to-br from-emerald-950 via-slate-900 to-slate-950 p-6 text-white shadow-lg md:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><div className="mb-3 flex items-center gap-2 text-sm text-emerald-200"><Link2 className="size-4" />SEO yönetimi</div><h1 className="text-3xl font-bold tracking-tight">URL ve yönlendirmeler</h1><p className="mt-2 max-w-2xl text-sm text-slate-300">Kırık bağlantıları yönetin, URL envanterini görün ve arama motoru değerini doğru adrese taşıyın.</p></div><Button className="bg-white text-slate-900 hover:bg-slate-100" onClick={()=>{setEditing(null);setForm(blank)}}><Plus className="mr-2 size-4" />Yeni yönlendirme</Button></div><div className="mt-7 grid grid-cols-3 gap-3 border-t border-white/10 pt-5"><div><p className="text-xs text-slate-400">Aktif yönlendirme</p><p className="mt-1 text-xl font-semibold">{activeCount}</p></div><div><p className="text-xs text-slate-400">301 kalıcı kural</p><p className="mt-1 text-xl font-semibold">{redirects.filter(item=>item.statusCode===301).length}</p></div><div><p className="text-xs text-slate-400">Yayınlanan URL</p><p className="mt-1 text-xl font-semibold">{data.totalCount}</p></div></div></div>
    {message&&<div className="flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-900"><CheckCircle2 className="size-4" />{message}</div>}
    <Card className="border-slate-200 p-5 shadow-sm md:p-7"><div className="mb-6 flex items-start justify-between border-b pb-5"><div><h2 className="text-xl font-bold text-slate-900">{editing?"Yönlendirmeyi düzenle":"Yeni yönlendirme"}</h2><p className="mt-1 text-sm text-muted-foreground">Kaynak URL’nin başına alan adı yazmayın; örnek: <code>/eski-urun</code>.</p></div>{editing&&<Button variant="ghost" onClick={()=>{setEditing(null);setForm(blank)}}><X className="mr-2 size-4" />İptal</Button>}</div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><div className="space-y-1.5"><Label>Kaynak URL</Label><Input placeholder="/eski-urun" value={form.sourcePath} onChange={e=>setForm({...form,sourcePath:e.target.value})} /></div><div className="space-y-1.5"><Label>Hedef URL</Label><Input placeholder="/yeni-urun" value={form.targetPath} onChange={e=>setForm({...form,targetPath:e.target.value})} /></div><div className="space-y-1.5"><Label>Yönlendirme türü</Label><select className="h-10 w-full rounded-md border bg-white px-3 text-sm" value={form.statusCode} onChange={e=>setForm({...form,statusCode:Number(e.target.value)})}><option value={301}>301 — Kalıcı</option><option value={302}>302 — Geçici</option></select></div><div className="flex items-end gap-3"><Button className="flex-1" onClick={save}>Kaydet</Button><label className="flex h-10 items-center gap-2 whitespace-nowrap text-sm"><Switch checked={form.isActive} onCheckedChange={value=>setForm({...form,isActive:value})} />Aktif</label></div></div>{normalizedPreview&&<div className="mt-4 flex items-center gap-2 rounded-lg bg-slate-50 px-4 py-3 text-sm"><Link2 className="size-4 text-emerald-700" /><span className="font-mono text-slate-700">{normalizedPreview}</span><Badge variant="secondary">{form.statusCode}</Badge></div>}</Card>
    <Card className="overflow-hidden border-slate-200 shadow-sm"><div className="flex flex-col gap-4 border-b p-5 md:flex-row md:items-center md:justify-between md:px-7"><div><h2 className="font-bold text-slate-900">Yönlendirme kuralları</h2><p className="mt-1 text-sm text-muted-foreground">Kalıcı yönlendirmeler SEO değerini yeni adrese aktarır.</p></div><Badge variant="secondary">{redirects.length} kural</Badge></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 md:px-7">Kaynak</th><th className="px-5 py-3">Hedef</th><th className="px-5 py-3">Tür</th><th className="px-5 py-3">Durum</th><th className="px-5 py-3 md:px-7" /></tr></thead><tbody>{redirects.length?redirects.map(item=><tr key={item.id} className="border-t transition-colors hover:bg-slate-50/80"><td className="px-5 py-4 font-mono text-slate-700 md:px-7">{item.sourcePath}</td><td className="px-5 py-4 font-mono text-slate-700">{item.targetPath}</td><td className="px-5 py-4"><Badge className={item.statusCode===301?"bg-emerald-100 text-emerald-800 hover:bg-emerald-100":"bg-amber-100 text-amber-800 hover:bg-amber-100"}>{item.statusCode} {item.statusCode===301?"Kalıcı":"Geçici"}</Badge></td><td className="px-5 py-4"><Badge variant={item.isActive?"default":"secondary"}>{item.isActive?"Aktif":"Pasif"}</Badge></td><td className="px-5 py-4 text-right md:px-7"><Button size="sm" variant="outline" onClick={()=>edit(item)}><Pencil className="mr-1.5 size-3.5" />Düzenle</Button><Button size="icon" variant="ghost" className="ml-1 text-rose-600 hover:bg-rose-50 hover:text-rose-700" onClick={()=>setDeleteTarget(item)} aria-label="Yönlendirmeyi sil"><Trash2 className="size-4" /></Button></td></tr>):<tr><td colSpan={5} className="px-5 py-12 text-center text-muted-foreground">Henüz yönlendirme kuralı oluşturulmamış.</td></tr>}</tbody></table></div></Card>
    <Card className="overflow-hidden border-slate-200 shadow-sm"><div className="flex flex-col gap-4 border-b p-5 md:flex-row md:items-center md:justify-between md:px-7"><div><div className="flex items-center gap-2"><FileSearch className="size-5 text-emerald-700" /><h2 className="font-bold text-slate-900">Yayınlanan URL envanteri</h2></div><p className="mt-1 text-sm text-muted-foreground">Ürün ve kategori URL’lerini arayın veya veriyi yeniden oluşturun.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void load()} disabled={loading}><Search className="mr-2 size-4" />Ara</Button><Button variant="outline" onClick={()=>void rebuild()} disabled={rebuilding}><RefreshCw className={`mr-2 size-4 ${rebuilding?"animate-spin":""}`} />Yeniden oluştur</Button></div></div><div className="p-5 md:px-7"><div className="relative max-w-lg"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="pl-9" placeholder="Slug ara; örn. ilk-adim-makosen" value={q} onChange={e=>setQ(e.target.value)} /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[520px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 md:px-7">URL</th><th className="px-5 py-3">Tür</th><th className="px-5 py-3 md:px-7" /></tr></thead><tbody>{loading?<tr><td colSpan={3} className="px-5 py-10 text-center text-muted-foreground">URL’ler yükleniyor…</td></tr>:data.items.length?data.items.map(item=><tr key={item.id} className="border-t"><td className="px-5 py-3 font-mono text-slate-700 md:px-7">/{item.slug}</td><td className="px-5 py-3"><Badge variant="secondary">{item.entityType}</Badge></td><td className="px-5 py-3 text-right md:px-7"><a href={`/${item.slug}`} target="_blank" rel="noreferrer"><Button size="sm" variant="ghost"><ExternalLink className="mr-1.5 size-3.5" />Aç</Button></a></td></tr>):<tr><td colSpan={3} className="px-5 py-10 text-center text-muted-foreground"><AlertCircle className="mx-auto mb-2 size-6 text-slate-300" />Sonuç bulunamadı.</td></tr>}</tbody></table></div></Card>
    <AlertDialog open={!!deleteTarget} onOpenChange={open=>!open&&setDeleteTarget(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Yönlendirme silinsin mi?</AlertDialogTitle><AlertDialogDescription>Bu kural kaldırıldığında eski URL artık hedef sayfaya yönlendirilmez.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Vazgeç</AlertDialogCancel><AlertDialogAction className="bg-rose-600 hover:bg-rose-700" onClick={()=>void remove()}><Trash2 className="mr-2 size-4" />Sil</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </main>
}
