"use client"
import { useEffect, useState } from "react"
import Image from "next/image"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { fetchApi, imagesApi } from "@/lib/api"

type Hero = { heroEyebrow?:string; heroTitle?:string; heroSummary?:string; primaryCtaLabel?:string; primaryCtaHref?:string; secondaryCtaLabel?:string; secondaryCtaHref?:string; heroImageUrl?:string; heroImageAlt?:string }
const defaults: Required<Pick<Hero,"heroEyebrow"|"heroTitle"|"heroSummary"|"primaryCtaLabel"|"primaryCtaHref"|"secondaryCtaLabel"|"secondaryCtaHref">> = { heroEyebrow:"Evinizin iklimi, uzman kontrolünde",heroTitle:"Her mevsim doğru konfor.",heroSummary:"Isı pompası, klima, kombi ve kazan çözümlerini ihtiyacınıza uygun seçin.",primaryCtaLabel:"Ürünleri incele",primaryCtaHref:"/kategori/kombi",secondaryCtaLabel:"Ücretsiz keşif planla",secondaryCtaHref:"/kesif" }
export default function HomeHeroPage(){const [hero,setHero]=useState<Hero>(defaults);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);useEffect(()=>{void fetchApi<Hero>("/admin/home/settings/hero").then(v=>setHero(x=>({...x,...v}))).catch(()=>setMessage("Ayarlar yüklenemedi."))},[]);const set=(key:keyof Hero,value:string)=>setHero(x=>({...x,[key]:value}));const upload=async(file:File)=>{setBusy(true);try{const r=await imagesApi.uploadImage(file,"Ana sayfa hero","Ana sayfa hero");if(!r.data?.url)throw new Error();set("heroImageUrl",r.data.url);setMessage("Görsel yüklendi; Kaydet ile yayına alın.")}catch{setMessage("Görsel yüklenemedi.")}finally{setBusy(false)}};const save=async()=>{setBusy(true);try{await fetchApi("/admin/home/settings/hero",{method:"POST",body:JSON.stringify(hero)});setMessage("Hero kaydedildi.")}catch{setMessage("Hero kaydedilemedi.")}finally{setBusy(false)}};return <div className="mx-auto max-w-5xl space-y-6 pb-10"><div className="rounded-2xl bg-gradient-to-r from-emerald-950 to-emerald-700 p-7 text-white"><h1 className="text-3xl font-bold">Ana sayfa hero</h1><p className="mt-2 text-sm text-emerald-100">Görsel, başlık, açıklama ve butonları mağaza ana sayfası için yönetin.</p></div><div className="grid gap-5 rounded-xl border bg-white p-6 md:grid-cols-2">{([['heroEyebrow','Üst başlık'],['heroTitle','Başlık'],['primaryCtaLabel','Birincil buton'],['primaryCtaHref','Birincil bağlantı'],['secondaryCtaLabel','İkincil buton'],['secondaryCtaHref','İkincil bağlantı'],['heroImageAlt','Görsel açıklaması']] as [keyof Hero,string][]).map(([key,label])=><label key={key} className="space-y-2"><Label>{label}</Label><Input value={hero[key]||""} onChange={e=>set(key,e.target.value)}/></label>)}<label className="space-y-2 md:col-span-2"><Label>Açıklama</Label><textarea className="min-h-24 w-full rounded-md border p-3 text-sm" value={hero.heroSummary||""} onChange={e=>set("heroSummary",e.target.value)}/></label><div className="space-y-2 md:col-span-2"><Label>Hero görseli</Label><Input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0])}/><p className="text-xs text-muted-foreground">Görseli dosyadan seçin. Link yazmanız gerekmez.</p>{hero.heroImageUrl&&<Image className="mt-3 max-h-64 rounded-lg object-cover" src={hero.heroImageUrl} alt="Hero önizleme" width={1000} height={450}/>}</div><div className="flex items-center gap-3 md:col-span-2"><Button onClick={()=>void save()} disabled={busy}>{busy?"İşleniyor…":"Kaydet ve yayınla"}</Button>{message&&<p className="text-sm text-muted-foreground">{message}</p>}</div></div></div>}
