"use client"

import { useEffect, useMemo, useState, type ReactNode } from "react"
import { CheckCircle2, Eye, EyeOff, LockKeyhole, Save, ShieldCheck, TriangleAlert } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { fetchApi } from "@/lib/api"

type Settings={isMetaServerSideEnabled:boolean;isGoogleServerSideEnabled:boolean;isTikTokServerSideEnabled:boolean;hasMetaAccessToken:boolean;hasGoogleMeasurementProtocolApiSecret:boolean;hasTikTokAccessToken:boolean;googleAdsConversionId?:string}
type Tokens={metaAccessToken:string;googleMeasurementProtocolApiSecret:string;googleAdsConversionId:string;tikTokAccessToken:string}
const defaults:Settings={isMetaServerSideEnabled:false,isGoogleServerSideEnabled:false,isTikTokServerSideEnabled:false,hasMetaAccessToken:false,hasGoogleMeasurementProtocolApiSecret:false,hasTikTokAccessToken:false}

export default function TrackingSettingsPage(){
 const [settings,setSettings]=useState<Settings>(defaults);const [tokens,setTokens]=useState<Tokens>({metaAccessToken:"",googleMeasurementProtocolApiSecret:"",googleAdsConversionId:"",tikTokAccessToken:""});const [message,setMessage]=useState("");const [loading,setLoading]=useState(true);const [show,setShow]=useState<Record<string,boolean>>({})
 useEffect(()=>{fetchApi<Settings>("admin/marketing/server-side-settings").then(value=>{setSettings(value);setTokens(current=>({...current,googleAdsConversionId:value.googleAdsConversionId??""}))}).catch(()=>setMessage("Ayarlar yüklenemedi.")).finally(()=>setLoading(false))},[])
 const configured=useMemo(()=>[settings.hasMetaAccessToken,settings.hasGoogleMeasurementProtocolApiSecret&&!!settings.googleAdsConversionId,settings.hasTikTokAccessToken].filter(Boolean).length,[settings])
 const save=async()=>{try{const updated=await fetchApi<Settings>("admin/marketing/server-side-settings",{method:"POST",body:JSON.stringify({...settings,...tokens})});setSettings(updated);setTokens(current=>({...current,metaAccessToken:"",googleMeasurementProtocolApiSecret:"",tikTokAccessToken:""}));setMessage("Ayarlar kaydedildi. Gizli anahtarlar güvenlik nedeniyle yeniden gösterilmez.")}catch(error){setMessage(error instanceof Error?error.message:"Ayarlar kaydedilemedi.")}}
 const field=(key:keyof Tokens,label:string,configured:boolean,help:string)=> <div className="space-y-1.5"><div className="flex items-center justify-between"><Label className="text-sm font-medium">{label}</Label>{configured?<Badge className="bg-emerald-100 text-emerald-800 hover:bg-emerald-100">Tanımlı</Badge>:<Badge variant="secondary">Eksik</Badge>}</div><div className="relative"><Input type={key==="googleAdsConversionId"||show[key]?"text":"password"} className={key==="googleAdsConversionId"?"":"pr-10"} value={tokens[key]} onChange={event=>setTokens({...tokens,[key]:event.target.value})} placeholder={configured?"Değiştirmek için yeni değer girin":"Değer girin"} autoComplete="off" />{key!=="googleAdsConversionId"&&<Button type="button" size="icon" variant="ghost" className="absolute right-0 top-0 h-10 w-10" onClick={()=>setShow({...show,[key]:!show[key]})}>{show[key]?<EyeOff className="size-4"/>:<Eye className="size-4"/>}</Button>}</div><p className="text-xs text-muted-foreground">{help}</p></div>
 const Platform=({name,description,enabled,enabledChange,ready,children,color}:{name:string;description:string;enabled:boolean;enabledChange:(value:boolean)=>void;ready:boolean;children:ReactNode;color:string})=><Card className="overflow-hidden border-slate-200 shadow-sm"><div className={`h-1 ${color}`}/><div className="p-5 md:p-6"><div className="flex flex-col gap-4 border-b pb-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><h2 className="text-lg font-bold text-slate-900">{name}</h2><Badge className={ready?"bg-emerald-100 text-emerald-800 hover:bg-emerald-100":"bg-amber-100 text-amber-800 hover:bg-amber-100"}>{ready?"Bağlantı hazır":"Yapılandırma gerekli"}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{description}</p></div><label className="flex items-center gap-2 whitespace-nowrap text-sm font-medium"><Switch checked={enabled} onCheckedChange={enabledChange} disabled={loading}/>{enabled?"Etkin":"Pasif"}</label></div><div className="mt-5">{children}</div></div></Card>
 return <main className="mx-auto max-w-5xl space-y-6 pb-10"><div className="rounded-2xl bg-gradient-to-br from-slate-950 via-indigo-950 to-violet-950 p-6 text-white shadow-lg md:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><div className="mb-3 flex items-center gap-2 text-sm text-violet-200"><ShieldCheck className="size-4"/>Gizlilik odaklı ölçüm</div><h1 className="text-3xl font-bold tracking-tight">Server-side dönüşüm ayarları</h1><p className="mt-2 max-w-2xl text-sm text-slate-300">Tarayıcı engellese bile sipariş dönüşümlerini Meta, Google ve TikTok’a sunucu üzerinden iletin.</p></div><div className="rounded-xl border border-white/10 bg-white/10 px-4 py-3"><p className="text-xs text-slate-300">Hazır platform</p><p className="mt-1 text-xl font-semibold">{configured} / 3</p></div></div></div>
 {message&&<div className="flex items-center gap-2 rounded-lg border border-violet-200 bg-violet-50 px-4 py-3 text-sm text-violet-900"><CheckCircle2 className="size-4"/>{message}</div>}<div className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><TriangleAlert className="mt-0.5 size-4 shrink-0"/><p>Anahtarlar şifreli ayarlarda tutulur ve kaydedildikten sonra tekrar gösterilmez. Bir anahtarı boş bırakmak mevcut kayıtlı anahtarı silmez.</p></div>
 <Platform name="Meta Conversions API" description="Meta Pixel dönüşümlerinin sunucu taraflı eşlemesi." enabled={settings.isMetaServerSideEnabled} enabledChange={value=>setSettings({...settings,isMetaServerSideEnabled:value})} ready={settings.hasMetaAccessToken} color="bg-blue-600">{field("metaAccessToken","Conversions API access token",settings.hasMetaAccessToken,"Meta Events Manager içinden oluşturulan erişim anahtarı.")}</Platform>
 <Platform name="Google Measurement Protocol" description="GA4 ve Google Ads dönüşümlerinin sunucu taraflı gönderimi." enabled={settings.isGoogleServerSideEnabled} enabledChange={value=>setSettings({...settings,isGoogleServerSideEnabled:value})} ready={settings.hasGoogleMeasurementProtocolApiSecret&&!!settings.googleAdsConversionId} color="bg-emerald-600"><div className="grid gap-5 md:grid-cols-2">{field("googleMeasurementProtocolApiSecret","Measurement Protocol API secret",settings.hasGoogleMeasurementProtocolApiSecret,"GA4 veri akışındaki Measurement Protocol gizli anahtarı.")}{field("googleAdsConversionId","Google Ads conversion ID",!!settings.googleAdsConversionId,"Örn. AW-123456789. Google Ads dönüşüm eşlemesi için gereklidir.")}</div></Platform>
 <Platform name="TikTok Events API" description="TikTok pixel dönüşümlerinin sunucu taraflı Events API ile gönderimi." enabled={settings.isTikTokServerSideEnabled} enabledChange={value=>setSettings({...settings,isTikTokServerSideEnabled:value})} ready={settings.hasTikTokAccessToken} color="bg-slate-800">{field("tikTokAccessToken","Events API access token",settings.hasTikTokAccessToken,"TikTok Events Manager üzerinden oluşturulan erişim anahtarı.")}</Platform>
 <div className="sticky bottom-4 flex items-center justify-between gap-4 rounded-xl border bg-white/95 p-4 shadow-lg backdrop-blur"><div className="flex items-center gap-2 text-sm text-muted-foreground"><LockKeyhole className="size-4"/>Değişiklikler güvenli şekilde kaydedilir.</div><Button onClick={()=>void save()} disabled={loading}><Save className="mr-2 size-4"/>Ayarları kaydet</Button></div>
 </main>
}
